In [1]:
import numpy as np

# 创建数组

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [7]:
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [8]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
def arrayAdd(n):
    a = np.arange(1, n + 1) ** 3
    b = np.arange(1, n + 1) ** 2
    return a + b

print(arrayAdd(3))

[ 2 12 36]


In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(range(1, 6))
c = np.arange(1, 6)     # 推荐
print(a)
print(b)
print(c)
print(a.dtype)
print(type(a))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


`dtype`

`ndim`  维度的数目

`shape` 维度--几行几列

`size`

### `ones` 创建全是1的数组

In [13]:
a = np.ones(3)
a

array([1., 1., 1.])

In [14]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [18]:
d = np.full(fill_value=527, shape=(3, 4))

In [19]:
d

array([[527, 527, 527, 527],
       [527, 527, 527, 527],
       [527, 527, 527, 527]])

In [20]:
e = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(e)

[[1 2 3]
 [4 5 6]]


In [21]:
b = np.full(shape=(2, 3, 4), fill_value=527)
b

array([[[527, 527, 527, 527],
        [527, 527, 527, 527],
        [527, 527, 527, 527]],

       [[527, 527, 527, 527],
        [527, 527, 527, 527],
        [527, 527, 527, 527]]])

In [23]:
print(b.dtype)
print(b.size)
print(b.shape)
print(b.ndim)

int32
24
(2, 3, 4)
3


In [24]:
x = np.ones_like(b)
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

# random模块生成随机数

In [27]:
a = np.random.rand()
b = np.random.rand(3)
c = np.random.rand(3, 2)
d = np.random.rand(3, 2 ,4)
print(a)
print("------------")
print(b)
print("------------")
print(c)
print("------------")
print(d)

0.4199506647056037
------------
[0.30817209 0.60051018 0.39474796]
------------
[[0.50948021 0.43009223]
 [0.73070743 0.15260719]
 [0.86525019 0.51533095]]
------------
[[[0.28775583 0.84178332 0.27131351 0.84673642]
  [0.58821663 0.62386725 0.22204485 0.75045544]]

 [[0.99199269 0.97747421 0.34735542 0.82843288]
  [0.07243611 0.11709367 0.69316821 0.69302611]]

 [[0.79144009 0.20258183 0.49057073 0.60877667]
  [0.51428366 0.36923925 0.13892728 0.11198074]]]
