In [8]:
import numpy as np
arr1 = np.random.randint(0, 10, size=(1, 3))
arr2 = np.random.randint(0, 10, size=(1, 3))
arr3 = np.random.random((3, 2))
arr4 = np.random.normal(size=(3, 2))
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[[3 9 0]]
[[1 7 4]]
[[0.81448709 0.93487469]
 [0.58537758 0.08150978]
 [0.30754328 0.73155116]]
[[ 0.39157047  0.38105572]
 [-0.83178989 -0.26064485]
 [ 1.10659911  1.03067674]]


In [10]:
new_arr = np.vstack((arr1, arr2))

In [11]:
new_arr

array([[3, 9, 0],
       [1, 7, 4]])

In [12]:
new_arr2 = np.hstack((arr1, arr2))
new_arr2

array([[3, 9, 0, 1, 7, 4]])

In [28]:
new_arr3 = np.concatenate((arr2, arr1), axis=0)
new_arr4 = np.concatenate((arr2, arr1), axis=1)
print(new_arr3)
print(new_arr4)

[[1 7 4]
 [3 9 0]]
[[1 7 4 3 9 0]]


In [14]:
arr = np.random.randint(0, 20, size=(3, 5))

In [15]:
print(arr)

[[13 15  1 12 14]
 [ 1 19  9 13 19]
 [15  2  7  0  1]]


In [16]:
arr = np.arange(10)

In [18]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr = arr[np.newaxis, :]
print(arr)

[[0 1 2 3 4 5 6 7 8 9]]


In [22]:
print(arr.T)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [23]:
generate_arr = np.atleast_2d(arr)

In [25]:
print(generate_arr)

[[0 1 2 3 4 5 6 7 8 9]]


In [27]:
generate_arr2 = np.atleast_3d(arr)
print(generate_arr2)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]
