In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a = np.arange(18).reshape(3, 2, 3)

In [7]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [8]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
a + b

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 6,  8, 10],
        [12, 14, 16]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [10]:
a = np.arange(18).reshape(3, 2, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [12]:
b = np.arange(9).reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
c = a + b
c

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [18]:
a = np.arange(12).reshape(3, 2, 2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
b = np.arange(2).reshape(2, 1)
b

array([[0],
       [1]])

In [21]:
c = a + b
c

array([[[ 0,  1],
        [ 3,  4]],

       [[ 4,  5],
        [ 7,  8]],

       [[ 8,  9],
        [11, 12]]])

In [22]:
a = np.arange(10)

In [23]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = a > 5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [44]:
a = np.arange(10)
# a[a>5] = 0
# a[a<=5] = 1
print(a)
a[a>5] = 1
# a[a<=5] = 0
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [38]:
a[a<=5] = 1
a[a>5] = 0

In [39]:
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [45]:
a = np.random.rand(3, 4)
a

array([[0.4724428 , 0.24022139, 0.99737522, 0.05406068],
       [0.48276601, 0.51599995, 0.68008527, 0.79418547],
       [0.97148986, 0.19332322, 0.04079657, 0.62205406]])

In [46]:
b = np.random.rand(4, 5)
b

array([[0.37753349, 0.27556797, 0.24665837, 0.47705371, 0.07631499],
       [0.87855961, 0.0405675 , 0.59183147, 0.81778546, 0.40004513],
       [0.60817719, 0.1946997 , 0.58368918, 0.90598217, 0.0747566 ],
       [0.68237463, 0.07263027, 0.78832624, 0.65790916, 0.08179497]])

In [47]:
c = a.dot(b)
c

array([[1.03288228, 0.33805038, 0.88347712, 1.36100133, 0.21113613],
       [1.59114141, 0.34406198, 1.44749894, 1.79092959, 0.35906678],
       [0.98590138, 0.32867716, 0.86823493, 1.06776579, 0.20540796]])

In [48]:
c.T

array([[1.03288228, 1.59114141, 0.98590138],
       [0.33805038, 0.34406198, 0.32867716],
       [0.88347712, 1.44749894, 0.86823493],
       [1.36100133, 1.79092959, 1.06776579],
       [0.21113613, 0.35906678, 0.20540796]])

In [50]:
np.transpose(c)
c

array([[1.03288228, 0.33805038, 0.88347712, 1.36100133, 0.21113613],
       [1.59114141, 0.34406198, 1.44749894, 1.79092959, 0.35906678],
       [0.98590138, 0.32867716, 0.86823493, 1.06776579, 0.20540796]])

In [51]:
np.sum(c)

12.815233170061646

In [52]:
c.argmax()

8

In [53]:
c.argmin()

14

In [55]:
np.median(c)

0.8834771221631832

In [57]:
np.clip(c, 0.22, 0.7)

array([[0.7       , 0.33805038, 0.7       , 0.7       , 0.22      ],
       [0.7       , 0.34406198, 0.7       , 0.7       , 0.35906678],
       [0.7       , 0.32867716, 0.7       , 0.7       , 0.22      ]])

In [58]:
for i in c:
    print(i)

[1.03288228 0.33805038 0.88347712 1.36100133 0.21113613]
[1.59114141 0.34406198 1.44749894 1.79092959 0.35906678]
[0.98590138 0.32867716 0.86823493 1.06776579 0.20540796]


In [60]:
for i in c.T:
    print(i)

[1.03288228 1.59114141 0.98590138]
[0.33805038 0.34406198 0.32867716]
[0.88347712 1.44749894 0.86823493]
[1.36100133 1.79092959 1.06776579]
[0.21113613 0.35906678 0.20540796]


In [61]:
for i in c.flat:
    print(i)

1.03288228155405
0.33805037648046815
0.8834771221631832
1.3610013348020522
0.21113613460755815
1.5911414077782626
0.3440619751072595
1.4474989375099372
1.7909295944717916
0.3590667833098824
0.9859013795874999
0.3286771636902089
0.8682349281233486
1.067765794532562
0.20540795634358208
