#  asdfasdf

sadhfuohasduiofhuasof

In [1]:
print(123)

123


In [6]:
a = 3

In [4]:
print(a)

3


In [7]:
a
import numpy as np

In [16]:
a = [[1, 2, 1, 3], [0, 0, 1, 4], [1, 0, 1, 5]]
b = [[1, 1, 0, 5], [0, 1, 0, 2], [0, 1, 2, 0], [6, 6, 6, 6]]
an = np.array(a)
bn = np.array(b)
print(an)

[[1 2 1 3]
 [0 0 1 4]
 [1 0 1 5]]


In [17]:
print(bn)

[[1 1 0 5]
 [0 1 0 2]
 [0 1 2 0]
 [6 6 6 6]]


In [18]:
print(np.dot(an, bn))

[[19 22 20 27]
 [24 25 26 24]
 [31 32 32 35]]
