In [2]:
import random
random.seed(3)
random.randint(1, 100)

31

In [3]:
random.randint(1, 100)

76

In [4]:
random.uniform(-100, 100)

8.845845059190367

In [6]:
round(random.uniform(-100, 100), 2)

25.14

In [7]:
import numpy as np
rand = np.random.RandomState(32)
x = rand.randint(0, 10, (3, 6))

In [8]:
x

array([[7, 5, 6, 8, 3, 7],
       [9, 3, 5, 9, 4, 1],
       [3, 1, 2, 3, 8, 2]])

In [9]:
y = rand.rand(5) * 10

In [10]:
y

array([4.41713488, 5.51487786, 7.03712491, 5.89401231, 0.49932759])

In [11]:
z = rand.rand(5) + 5

In [12]:
z

array([5.56179184, 5.76635847, 5.91090833, 5.09290995, 5.90252139])

In [13]:
x = np.linspace(2, 100, 40)

In [14]:
x

array([  2.        ,   4.51282051,   7.02564103,   9.53846154,
        12.05128205,  14.56410256,  17.07692308,  19.58974359,
        22.1025641 ,  24.61538462,  27.12820513,  29.64102564,
        32.15384615,  34.66666667,  37.17948718,  39.69230769,
        42.20512821,  44.71794872,  47.23076923,  49.74358974,
        52.25641026,  54.76923077,  57.28205128,  59.79487179,
        62.30769231,  64.82051282,  67.33333333,  69.84615385,
        72.35897436,  74.87179487,  77.38461538,  79.8974359 ,
        82.41025641,  84.92307692,  87.43589744,  89.94871795,
        92.46153846,  94.97435897,  97.48717949, 100.        ])

In [15]:
 ar1 = np.arange(1, 10)

In [16]:
ar1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
range(1, 10, 2)

range(1, 10, 2)

In [18]:
list(range(1, 10 ,2))

[1, 3, 5, 7, 9]

In [20]:
ar2 = np.array([1, 2, 3, 4, 5])

In [22]:
ar2

array([1, 2, 3, 4, 5])

In [23]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [26]:
ar3 = np.zeros((5, 5))

In [28]:
ar3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
ar4 = np.ones((5, 5))

In [30]:
ar4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.full((3, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [32]:
rand.randint(0, 100, [3, 5])

array([[64, 11,  6, 94, 68],
       [62, 30, 80, 83, 50],
       [74, 35, 61, 50, 45]])

In [33]:
np.zeros(shape=(2, 15), dtype=np.int)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3264\1441843178.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(shape=(2, 15), dtype=np.int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.ones((3, 5), dtype=np.float)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3264\94629147.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((3, 5), dtype=np.float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
myary = np.arange(0, 20)
myary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
myary[myary > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
print(myary)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
print(myary[:, np.newaxis])

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [42]:
print(myary[:, np.newaxis].shape)


(20, 1)


In [43]:
b = np.arange(1, 21).reshape(5, 4)

In [44]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
print(b[[2, 4], 3])

[12 20]
